
//GET ALL PRODUCTS
GET http://localhost:5000/api/products


###
//CREATE PRODUCT
POST http://localhost:5000/api/products
Content-Type: application/json

{"brand":"6143e6f71d37095e32c25e45",
"category":"Air Jordan One",
"colorway":"Black/White-Lights Sdmoke Grey",
"condition":"New",
"countryOfManufacture":"CN",
"description":"The upper of the Air Jordan 1 Shadow 2.0 is made of a black leather base with Light Smoke Grey overlays. A classic Wings logo appears on the lateral ankle wrap while a woven Nike Air label is stitched atop the tongue to complete the look.\n<br>\n<br>\nThe Air Jordan 1 Shadow 2.0 released in May of 2021 and retailed for $170.",
"gender":"men",
"media":{"imageUrl":"https://images.stockx.com/images/Air-Jordan-1-Retro-High-Black-White-Light-Smoke-Grey-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1621454319","smallImageUrl":"https://images.stockx.com/images/Air-Jordan-1-Retro-High-Black-White-Light-Smoke-Grey-Product.jpg?fit=fill&bg=FFFFFF&w=300&h=214&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1621454319","thumbUrl":"https://images.stockx.com/images/Air-Jordan-1-Retro-High-Black-White-Light-Smoke-Grey-Product.jpg?fit=fill&bg=FFFFFF&w=140&h=100&auto=format,compress&trim=color&q=90&dpr=2&updated_at=1621454319"},
"name":" Shadow 2.0",
"productCategory": "6143e7061d37095e32c25e47",
"releaseDate":"2021-05-15",
"retailPrice":170,
"shoe":"Jordan 1 Retro High",
"shortDescription":"Air-Jordan-1-Retro-High-Black-White-Light-Smoke-Grey",
"styleId":"555088-035",
"title":"Jordan 1 Retro High Shadow e2.d0",
"year":2012,
"tags":["sneakers","jordan","air jordan","one","release_date|2021-05-15","colorway|black/white-light smoke grey","retail_price|170","style_id|555088-035"],
"test": "hahaa"
}

###
// GET PRODUCT
GET http://localhost:5000/api/products/6143e7141d3709s49

###
//UPDATE PRODUCT
PATCH  http://localhost:5000/api/products/6143e7141d37095e32c25e49
Content-Type: application/json

{
    "name": "",
    "retailPrice": 200
}

###
//DELETE PRODUCT

DELETE http://localhost:5000/api/products/6143c26ea9c4f286e4c94cd0


###
//CREATE BRAND
POST http://localhost:5000/api/brands
Content-Type: application/json

{
    "name": "Jordan"
}

###
//CREATE CATEGORY
POST http://localhost:5000/api/categories
Content-Type: application/json

{
    "name": "handbags"
}