const express = require('express')
const viewController = require('../controllers/viewController')
const authController = require('../controllers/authController')
const router = express.Router()

router.route('/search').get(viewController.searchProducts)
router.route('/add-following').post(authController.protect, viewController.addFollowingProduct)
router.route('/delete-following/:followingId').delete(authController.protect, viewController.deleteFollowingProduct)
router.route('/get-following/:userId').get(viewController.getFollowingProducts)
router.route('/top-5-newest-sneakers').get(viewController.getNewestSneakers)
router.route('/top-5-newest-streetwear').get(viewController.getNewestStreetwear)
router.route('/top-5-newest-collectibles').get(viewController.getNewestCollectibles)
router.route('/get-user-bids/:userId').get(viewController.getUserBids)
router.route('/get-user-asks/:userId').get(viewController.getUserAsks)
router.route('/get-buying-pending/:userId').get(viewController.getBuyingPending)
router.route('/get-asking-pending/:userId').get(viewController.getAskingPending)
router.route('/get-buying-history/:userId').get(viewController.getBuyingHistory)
router.route('/get-asking-history/:userId').get(viewController.getAskingHistory)
router.route('/:slug').get(viewController.getProductDetail)
router.route('/order/:slug').get(viewController.getAskAndBid)
module.exports = router